# Generated by Django 3.1 on 2020-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_process', '0002_documentmodel_labelindocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelindocument',
            name='end_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelindocument',
            name='end_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelindocument',
            name='start_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelindocument',
            name='start_y',
            field=models.FloatField(),
        ),
    ]
