# Generated by Django 3.1 on 2020-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_process', '0003_auto_20200928_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
