# Generated by Django 3.1 on 2020-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_process', '0004_auto_20200928_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.TextField(unique=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
